codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        # Adjusted after moving integration tests to separate phase
        # Project coverage reflects unit test coverage only
        target: 70%
        threshold: 1%
        if_ci_failed: error
    patch:
      default:
        # New code should maintain high coverage standards
        target: 80%
        threshold: 1%
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,tree,files"
  behavior: default
  require_changes: false

ignore:
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "**/test/**"
  - "**/tests/**"
  - "**/*.d.ts"
  - "**/dist/**"
  - "**/node_modules/**"
  - "tools/**"
  - "docs/**"
  - "**/*.config.ts"
  - "**/*.config.js"
