/**
 * Apply plugin-level files[] mapping (compiled artifacts injection).
 *
 * Constraints (spec section Design + Ordering contract phase 4):
 *   - dest must not resolve outside pluginOutputDir (no ".." escape)
 *   - dest must not resolve inside skills/ (owned by skill-stream)
 *   - dest must not target .claude-plugin/plugin.json (owned by merge-write)
 *   - parent dirs are created automatically
 *   - overwrites are allowed and logged at info level
 */

import { existsSync } from 'node:fs';
import { copyFile, mkdir } from 'node:fs/promises';
import { dirname } from 'node:path';

import type { SkillFileEntry } from '@vibe-agent-toolkit/resources';
import { safePath, toForwardSlash } from '@vibe-agent-toolkit/utils';

export interface ApplyPluginFilesArgs {
  projectRoot: string;
  pluginOutputDir: string;
  entries: readonly SkillFileEntry[];
  info?: (message: string) => void;
}

function validateDest(rawDest: string, pluginOutputDir: string): string {
  const normalized = toForwardSlash(rawDest);
  if (normalized.startsWith('/')) {
    throw new Error(`plugin files[].dest must be relative; got absolute path: ${rawDest}`);
  }
  if (normalized.startsWith('skills/') || normalized === 'skills') {
    throw new Error(
      `plugin files[].dest "${rawDest}" resolves inside skills/ — that surface is owned ` +
        `by the skill-stream. Place the file under a skill's own files[] instead.`,
    );
  }
  if (normalized === '.claude-plugin/plugin.json') {
    throw new Error(
      `plugin files[].dest "${rawDest}" targets plugin.json — that file is generated by ` +
        `VAT from the merged manifest. Put your custom fields in .claude-plugin/plugin.json inside the plugin source dir.`,
    );
  }
  const resolved = safePath.resolve(pluginOutputDir, rawDest);
  const resolvedBase = safePath.resolve(pluginOutputDir);
  if (!toForwardSlash(resolved).startsWith(toForwardSlash(resolvedBase) + '/')) {
    throw new Error(
      `plugin files[].dest "${rawDest}" resolves outside plugin output dir (path traversal rejected)`,
    );
  }
  return resolved;
}

export async function applyPluginFiles(args: ApplyPluginFilesArgs): Promise<void> {
  const { projectRoot, pluginOutputDir, entries, info } = args;

  for (const entry of entries) {
    const sourceAbs = safePath.resolve(projectRoot, entry.source);
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- resolved from project root
    if (!existsSync(sourceAbs)) {
      throw new Error(
        `plugin files[].source not found: ${entry.source} (resolved to ${sourceAbs})`,
      );
    }
    const destAbs = validateDest(entry.dest, pluginOutputDir);

    // eslint-disable-next-line security/detect-non-literal-fs-filename -- validated above
    if (existsSync(destAbs) && info) {
      info(`plugin files[]: overwriting existing ${toForwardSlash(entry.dest)}`);
    }

    // eslint-disable-next-line security/detect-non-literal-fs-filename -- validated dest
    await mkdir(dirname(destAbs), { recursive: true });
    await copyFile(sourceAbs, destAbs);
  }
}
