/**
 * Apply plugin-level files[] mapping (compiled artifacts injection).
 *
 * Constraints (spec section Design + Ordering contract phase 4):
 *   - dest must not resolve outside pluginOutputDir (no ".." escape)
 *   - dest must not resolve inside skills/ (owned by skill-stream)
 *   - dest must not target .claude-plugin/plugin.json (owned by merge-write)
 *   - parent dirs are created automatically
 *   - overwrites are allowed and logged at info level
 */

import { existsSync } from 'node:fs';

import type { SkillFileEntry } from '@vibe-agent-toolkit/resources';
import { forEachInOrder, issueLocation, safePath, toForwardSlash, toForwardSlashAnyPlatform } from '@vibe-agent-toolkit/utils';

import { CommandRefusalError } from '../../../utils/command-refusal.js';
import { copyFileIntoMarketplace } from '../../../utils/marketplace-io.js';
import { requireInputPath } from '../../../utils/project-root-policy.js';


/** A `files[].dest` the config may not declare. */
function invalidDest(message: string): CommandRefusalError {
  return new CommandRefusalError('CONFIG_INVALID', message);
}

export interface ApplyPluginFilesArgs {
  projectRoot: string;
  pluginOutputDir: string;
  entries: readonly SkillFileEntry[];
  info?: (message: string) => void;
}

function validateDest(rawDest: string, pluginOutputDir: string): string {
  const normalized = toForwardSlashAnyPlatform(rawDest);
  if (normalized.startsWith('/')) {
    throw invalidDest(`plugin files[].dest must be relative; got absolute path: ${rawDest}`);
  }
  if (normalized.startsWith('skills/') || normalized === 'skills') {
    throw invalidDest(
      `plugin files[].dest "${rawDest}" resolves inside skills/ — that surface is owned ` +
        `by the skill-stream. Place the file under a skill's own files[] instead.`,
    );
  }
  if (normalized === '.claude-plugin/plugin.json') {
    throw invalidDest(
      `plugin files[].dest "${rawDest}" targets plugin.json — that file is generated by ` +
        `VAT from the merged manifest. Put your custom fields in .claude-plugin/plugin.json inside the plugin source dir.`,
    );
  }
  const resolved = safePath.resolve(pluginOutputDir, rawDest);
  const resolvedBase = safePath.resolve(pluginOutputDir);
  if (!toForwardSlash(resolved).startsWith(toForwardSlash(resolvedBase) + '/')) {
    throw invalidDest(
      `plugin files[].dest "${rawDest}" resolves outside plugin output dir (path traversal rejected)`,
    );
  }
  return resolved;
}

export async function applyPluginFiles(args: ApplyPluginFilesArgs): Promise<void> {
  const { projectRoot, pluginOutputDir, entries, info } = args;

  // In order: a later entry deliberately overwrites an earlier one's dest.
  await forEachInOrder(entries, async (entry) => {
    const sourceAbs = safePath.resolve(projectRoot, entry.source);
    // Project-relative, never absolute: this refusal is published on
    // machine-readable stdout, where an absolute path publishes the developer's
    // home directory into whatever issue or CI log it lands in.
    requireInputPath(sourceAbs, {
      code: 'INPUT_UNREADABLE',
      message: `plugin files[].source not found: ${entry.source} (resolved to ${issueLocation(sourceAbs, projectRoot) || '.'})`,
    });
    const destAbs = validateDest(entry.dest, pluginOutputDir);

    if (existsSync(destAbs) && info) {
      info(`plugin files[]: overwriting existing ${toForwardSlashAnyPlatform(entry.dest)}`);
    }

    await copyFileIntoMarketplace(
      sourceAbs,
      destAbs,
      `plugin files[].source ${issueLocation(sourceAbs, projectRoot) || '.'}`,
      `plugin files[].dest ${toForwardSlashAnyPlatform(entry.dest)}`,
    );
  });
}
