/**
 * Shared frontmatter validation logic
 *
 * Validates skill frontmatter (name format, description, reserved words, etc.)
 * Used by both validateSkill() and validateSkillForPackaging() to ensure
 * consistent validation regardless of entry point.
 *
 * @see https://code.claude.com/docs/en/skills — Official Claude Code skill frontmatter fields
 */


import { CODE_REGISTRY, type ValidationIssue } from '@vibe-agent-toolkit/schema';

import { AgentSkillFrontmatterSchema, VATAgentSkillFrontmatterSchema } from '../schemas/agent-skill-frontmatter.js';

import { VALIDATION_THRESHOLDS } from './validation-rules.js';

// Document-internal pointers. These name a place INSIDE the SKILL.md, so they
// belong in `ValidationIssue.field`, never in `location` — `location` is
// contractually the project-relative path of the file to open, and the two used
// to be conflated in this module (the exported entry points never received the
// skill path at all, so 'frontmatter' was the best they could say).
const FRONTMATTER_FIELD = 'frontmatter';
const FRONTMATTER_NAME_FIELD = 'frontmatter.name';
const FRONTMATTER_DESC_FIELD = 'frontmatter.description';

/**
 * Stamp the containing file onto every issue produced by the field-level
 * helpers below. They know WHICH FIELD is wrong; only the entry points know
 * WHICH FILE, so the two anchors are joined here, once.
 */
function anchoredTo(location: string, issues: ValidationIssue[]): ValidationIssue[] {
	return issues.map((issue) => ({ ...issue, location }));
}

/**
 * Validate frontmatter against the Agent Skill schema
 *
 * Checks name format (regex), description length, required fields, etc.
 *
 * @param frontmatter - Parsed frontmatter key-value pairs
 * @param isVATGenerated - Whether skill was generated by VAT (stricter schema)
 * @param location - Project-relative POSIX path of the SKILL.md these fields
 *   came from. Required: an issue that can only say "frontmatter" is
 *   unactionable in a multi-skill report.
 * @returns Array of validation issues found
 */
export function validateFrontmatterSchema(
	frontmatter: Record<string, unknown>,
	isVATGenerated: boolean,
	location: string,
): ValidationIssue[] {
	const issues: ValidationIssue[] = [];
	const schema = isVATGenerated ? VATAgentSkillFrontmatterSchema : AgentSkillFrontmatterSchema;
	const schemaResult = schema.safeParse(frontmatter);

	if (schemaResult.success) {
		return issues;
	}

	// Map Zod errors to our issue codes
	for (const error of schemaResult.error.errors) {
		const field = error.path.join('.');

		if (field === 'name' && !frontmatter['name']) {
			issues.push({
				severity: 'error',
				code: 'SKILL_MISSING_NAME',
				message: 'Required field "name" is missing',
				field: FRONTMATTER_FIELD,
				fix: 'Add "name" field to frontmatter',
			});
		} else if (field === 'description' && !frontmatter['description']) {
			issues.push({
				severity: 'error',
				code: 'SKILL_MISSING_DESCRIPTION',
				message: 'Required field "description" is missing',
				field: FRONTMATTER_FIELD,
				fix: 'Add "description" field to frontmatter',
			});
		} else if (field === 'name') {
			issues.push({
				severity: 'error',
				code: 'SKILL_NAME_INVALID',
				message: error.message,
				field: FRONTMATTER_NAME_FIELD,
				fix: 'Change name to lowercase alphanumeric with hyphens (e.g., "my-skill")',
			});
		} else if (field === 'description' && error.code === 'too_big') {
			issues.push({
				severity: 'error',
				code: 'SKILL_DESCRIPTION_TOO_LONG',
				message: `Description exceeds 1024 characters (actual: ${(frontmatter['description'] as string)?.length ?? 0})`,
				field: FRONTMATTER_DESC_FIELD,
				fix: 'Reduce description to 1024 characters or less',
			});
		}
	}

	return anchoredTo(location, issues);
}

/**
 * Validate additional frontmatter rules beyond schema
 *
 * Checks reserved words, XML tags, empty descriptions, etc.
 *
 * @param frontmatter - Parsed frontmatter key-value pairs
 * @param location - Project-relative POSIX path of the containing SKILL.md.
 * @returns Array of validation issues found
 */
export function validateFrontmatterRules(
	frontmatter: Record<string, unknown>,
	location: string,
): ValidationIssue[] {
	const issues: ValidationIssue[] = [];

	// Validate name field
	if (frontmatter['name'] && typeof frontmatter['name'] === 'string') {
		issues.push(...validateNameRules(frontmatter['name']));
	}

	// Validate description field
	if (frontmatter['description'] && typeof frontmatter['description'] === 'string') {
		issues.push(...validateDescriptionRules(frontmatter['description']));
	}

	// Detect non-standard frontmatter keys (agentskills.io + Claude Code allowed set)
	issues.push(...detectExtraFrontmatterFields(frontmatter));

	return anchoredTo(location, issues);
}

/**
 * The vendor rule is "Cannot contain XML tags"
 * (docs/external/anthropic-skill-authoring-best-practices.md:21,27), and those
 * docs never define "XML tag" nor mention angle brackets. This module's reading,
 * stated so it can be argued with:
 *
 * **A tag is markup, not an angle bracket** — and the corpus splits in two.
 *
 * 1. UNAMBIGUOUS MARKUP. Nothing in prose is shaped like it, so it fires
 *    wherever it appears, backticks included: a markup declaration or processing
 *    instruction (`<!--`, `<![CDATA[`, `<!DOCTYPE`, `<?xml`), a closing tag
 *    (`</x>`), a self-closing tag (`<x/>`, `<x a/>`), and an opening tag that
 *    carries an ATTRIBUTE ASSIGNMENT (`<div class="x">`). Angle brackets holding
 *    prose with no `=` in them are not a tag: `<see https://example.com>` and
 *    `<y and y>` are a URL and a comparison.
 *
 * 2. AN AMBIGUOUS BARE `<word>`. `<example>` and `<env>` are the same four
 *    characters; no rule can tell a tag from a placeholder here. It therefore
 *    fires — the reading that keeps real tags firing — UNLESS it reads as part
 *    of a path or identifier (`skills/<name>/SKILL.md`, `Promise<Result>`,
 *    `repo#<n>`), and the author can mark it as quoted text with backticks,
 *    which is what the `fix:` text tells them to do. A consequence worth
 *    naming: a free-standing `<owner>` in `<owner>/<repo>#<n>` fires, because it
 *    is character-for-character what `<example>/<example>` is, and that one must
 *    fire. Backticking the whole template clears it.
 *
 * Backticks exempt only class 2. A code span may HIDE markup from the eye, but
 * it must never EXEMPT it: backticks in a description are unpaired often enough
 * that any pairing rule — naive or CommonMark-exact — can be made to swallow a
 * real tag (`` ` then <b>x</b> and a final ` `` is ONE span).
 */

/** An inline code span (`` `...` ``): the author marking content as quoted text. */
const INLINE_CODE_SPAN = /`[^`]*`/g;

/** `<!--`, `<![CDATA[`, `<!DOCTYPE`, `<?xml` — markup, never prose. */
const MARKUP_DECLARATION = /<\?|<!(?:--|\[|[A-Za-z])/;

/**
 * One `<…>` group, to be classified by {@link scanAngleGroups}. `[A-Za-z]` is a
 * single character and `[^<>]*` is the only quantifier, so the two cannot split
 * one run between them — the ambiguity that makes an adjacent pair of stars
 * quadratic. Each start position scans only as far as the next `<` or `>`.
 */
const ANGLE_GROUP = /<(\/?)([A-Za-z][^<>]*)>/g;

/** The tag-name prefix of a group body; the remainder is its attribute run. */
const TAG_NAME_PREFIX = /^[A-Za-z][\w.:-]*/;

/** A character that continues a path or identifier through a `<…>` group. */
const TOKEN_CHAR = /[\w/.\\:#@-]/;

/** A literal path segment — what has to follow `<name>/` for it to be a path. */
const PATH_SEGMENT_CHAR = /[\w.]/;

const WORD_CHAR = /\w/;

/**
 * Every pattern that scans unbounded author text. Exported for the backtracking
 * guard in `test/validators/frontmatter-validation.test.ts`, which runs each one
 * under a deadline `node:vm` can enforce — a guard that reads the list cannot go
 * blind to a pattern added later.
 */
export const XML_TAG_SCAN_PATTERNS: readonly RegExp[] = [
	INLINE_CODE_SPAN,
	MARKUP_DECLARATION,
	ANGLE_GROUP,
	TAG_NAME_PREFIX,
];

interface AngleScan {
	/** Class 1 above: markup, whatever it is wrapped in. */
	markup: boolean;
	/** Class 2 above: a bare `<word>` that does not read as a path or identifier. */
	bareTag: boolean;
}

/**
 * Whether a `<word>` at `index` reads as a tag rather than as a placeholder
 * inside a larger token.
 */
function isBareTagInProse(text: string, index: number, length: number): boolean {
	const before = index === 0 ? '' : text.charAt(index - 1);
	const end = index + length;
	const after = text.charAt(end);

	// `Promise<Result>`, `skills/<name>`, `list<item>`, `repo#<n>`: a token
	// continues on the left and the group is followed by punctuation or the end.
	// A WORD character after `>` means the group is glued into the middle of a
	// word (`in<thinking>mode`) — that is a tag, not a compound identifier.
	if (before !== '' && TOKEN_CHAR.test(before) && !WORD_CHAR.test(after)) {
		return false;
	}

	// `<name>/SKILL.md`: the path continues with a literal segment.
	// `<example>/<example>` continues with another group, so it is not a path —
	// an unconditional "followed by a slash" exemption is an escape hatch for
	// every tag.
	if ((after === '/' || after === '\\') && PATH_SEGMENT_CHAR.test(text.charAt(end + 1))) {
		return false;
	}

	return true;
}

/** Classify a group body that is not a bare `<word>`. */
function isMarkupBody(closing: boolean, attributeRun: string): boolean {
	if (closing) {
		return attributeRun.trim() === '';
	}
	if (attributeRun.trimEnd().endsWith('/')) {
		return true;
	}
	// An attribute run with no assignment in it is prose between angle brackets.
	return attributeRun.includes('=');
}

function scanAngleGroups(text: string): AngleScan {
	const scan: AngleScan = { markup: MARKUP_DECLARATION.test(text), bareTag: false };

	for (const match of text.matchAll(ANGLE_GROUP)) {
		const body = match[2] ?? '';
		const attributeRun = body.slice((TAG_NAME_PREFIX.exec(body)?.[0] ?? '').length);
		if (match[1] !== '/' && attributeRun.trim() === '') {
			scan.bareTag ||= isBareTagInProse(text, match.index, match[0].length);
			continue;
		}
		scan.markup ||= isMarkupBody(match[1] === '/', attributeRun);
	}

	return scan;
}

function containsXmlTag(text: string): boolean {
	const raw = scanAngleGroups(text);
	if (raw.markup) {
		return true;
	}
	if (!text.includes('`')) {
		return raw.bareTag;
	}
	return scanAngleGroups(text.replaceAll(INLINE_CODE_SPAN, ' ')).bareTag;
}

function validateNameRules(name: string): ValidationIssue[] {
	const issues: ValidationIssue[] = [];
	const lowered = name.toLowerCase();

	if (lowered.includes('anthropic') || lowered.includes('claude')) {
		const registryEntry = CODE_REGISTRY.RESERVED_WORD_IN_NAME;
		issues.push({
			severity: registryEntry.defaultSeverity,
			code: 'RESERVED_WORD_IN_NAME',
			message: 'Name contains reserved word "anthropic" or "claude"',
			field: FRONTMATTER_NAME_FIELD,
			fix: registryEntry.fix,
			reference: registryEntry.reference,
		});
	}

	if (containsXmlTag(name)) {
		issues.push({
			severity: 'error',
			code: 'SKILL_NAME_XML_TAGS',
			message: 'Name contains XML tags',
			field: FRONTMATTER_NAME_FIELD,
			fix: 'Remove the XML/HTML tag from the name',
		});
	}

	return issues;
}

function validateDescriptionRules(description: string): ValidationIssue[] {
	const issues: ValidationIssue[] = [];

	if (containsXmlTag(description)) {
		issues.push({
			severity: 'error',
			code: 'SKILL_DESCRIPTION_XML_TAGS',
			message: 'Description contains XML tags',
			field: FRONTMATTER_DESC_FIELD,
			fix: 'Remove the XML/HTML tag from the description. If it is a literal placeholder such as `<env>` or `<owner>/<repo>`, wrap it in backticks to mark it as quoted text — backticks do not exempt real markup (`</x>`, `<x/>`, `<x a="b">`, `<!--`, `<?`), which must be removed.',
		});
	}

	if (description.trim() === '') {
		issues.push({
			severity: 'error',
			code: 'SKILL_DESCRIPTION_EMPTY',
			message: 'Description is empty',
			field: FRONTMATTER_DESC_FIELD,
			fix: 'Add description explaining what the skill does and when to use it',
		});
	}

	// Soft check: description exceeds Claude Code /skills display limit (250 chars)
	// Sits alongside the 1024-char hard schema limit as an earlier, softer warning.
	if (description.length > VALIDATION_THRESHOLDS.MAX_DESCRIPTION_CHARS_CLAUDE_CODE) {
		const registryEntry = CODE_REGISTRY.SKILL_DESCRIPTION_OVER_CLAUDE_CODE_LIMIT;
		issues.push({
			severity: registryEntry.defaultSeverity,
			code: 'SKILL_DESCRIPTION_OVER_CLAUDE_CODE_LIMIT',
			message: `Description is ${description.length} characters (Claude Code truncates at ${VALIDATION_THRESHOLDS.MAX_DESCRIPTION_CHARS_CLAUDE_CODE} in /skills listing)`,
			field: FRONTMATTER_DESC_FIELD,
			fix: registryEntry.fix,
			reference: registryEntry.reference,
		});
	}

	const fillerIssue = detectFillerOpener(description);
	if (fillerIssue !== null) {
		issues.push(fillerIssue);
	}

	const wrongPersonIssue = detectWrongPerson(description);
	if (wrongPersonIssue !== null) {
		issues.push(wrongPersonIssue);
	}

	return issues;
}

/**
 * Filler opener patterns that describe the skill-as-object rather than the behavior.
 * Anchored to the start of the trimmed description (case-insensitive).
 *
 * Note: `Use when <concrete trigger>` is allowed — that's Anthropic's recommended
 * pattern. Only `Use when you want to` / `Use when you need to` are flagged.
 */
const FILLER_OPENER_PATTERNS: readonly RegExp[] = [
	/^this\s+skill\b/i,
	/^a\s+skill\s+that\b/i,
	/^a\s+skill\s+which\b/i,
	/^used\s+to\b/i,
	/^use\s+when\s+you\s+want\s+to\b/i,
	/^use\s+when\s+you\s+need\s+to\b/i,
];

function detectFillerOpener(description: string): ValidationIssue | null {
	const trimmed = description.trimStart();
	const match = FILLER_OPENER_PATTERNS.find((pattern) => pattern.test(trimmed));
	if (match === undefined) {
		return null;
	}

	// Extract matched prefix for the error message
	const execResult = match.exec(trimmed);
	const matchedText = execResult?.[0] ?? '';
	const registryEntry = CODE_REGISTRY.SKILL_DESCRIPTION_FILLER_OPENER;
	return {
		severity: registryEntry.defaultSeverity,
		code: 'SKILL_DESCRIPTION_FILLER_OPENER',
		message: `Description opens with filler "${matchedText}..." — lead with a verb phrase or "Use when <concrete trigger>" instead`,
		field: FRONTMATTER_DESC_FIELD,
		fix: registryEntry.fix,
		reference: registryEntry.reference,
	};
}

/**
 * Wrong-person patterns: first-person (I/I'll/I'm) or conversational second-person
 * (You/You'll/You're) followed by a common verb/modal.
 *
 * Word-boundary anchored to avoid matches on `Iowa`, `Ionic`, etc.
 * Case-insensitive.
 */
const WRONG_PERSON_PRONOUNS = '(?:I|I\'ll|I\'m|I\'ve|You|You\'ll|You\'re|You\'ve)';
const WRONG_PERSON_VERBS = '(?:can|should|will|might|need|want|must|may|could|would|have|are|am)';
// eslint-disable-next-line security/detect-non-literal-regexp -- compile-time constant pattern, no user input
const WRONG_PERSON_PATTERN = new RegExp(
	String.raw`\b${WRONG_PERSON_PRONOUNS}\s+${WRONG_PERSON_VERBS}\b`,
	'i',
);

/**
 * Standard frontmatter field names, derived from the Zod schema so the
 * allowed set stays in sync with the spec. Covers both agentskills.io and
 * Claude Code fields.
 *
 * Uses `.keyof().options` (stable across Zod v3 and v4) rather than
 * `_def.shape`, which is a function getter in v3 but a plain object in v4.
 */
const STANDARD_FRONTMATTER_FIELDS: ReadonlySet<string> = new Set(
	AgentSkillFrontmatterSchema.keyof().options,
);

/**
 * Detect frontmatter keys that sit outside the standard agentskills.io + Claude
 * Code allowed set. Emits one `SKILL_FRONTMATTER_EXTRA_FIELDS` warning per
 * non-standard key.
 *
 * Exported so CLI call sites can opt in explicitly — `validateFrontmatterRules`
 * wires it in by default so every validator entry point reports the smell.
 */
export function detectExtraFrontmatterFields(
	frontmatter: Record<string, unknown>,
): ValidationIssue[] {
	const issues: ValidationIssue[] = [];
	const registryEntry = CODE_REGISTRY.SKILL_FRONTMATTER_EXTRA_FIELDS;

	for (const key of Object.keys(frontmatter)) {
		if (STANDARD_FRONTMATTER_FIELDS.has(key)) {
			continue;
		}
		issues.push({
			severity: registryEntry.defaultSeverity,
			code: 'SKILL_FRONTMATTER_EXTRA_FIELDS',
			message: `Frontmatter contains non-standard field "${key}"; use \`metadata.*\` for custom data.`,
			field: FRONTMATTER_FIELD,
			fix: registryEntry.fix,
			reference: registryEntry.reference,
		});
	}

	return issues;
}

function detectWrongPerson(description: string): ValidationIssue | null {
	const match = WRONG_PERSON_PATTERN.exec(description);
	if (match === null) {
		return null;
	}
	const registryEntry = CODE_REGISTRY.SKILL_DESCRIPTION_WRONG_PERSON;
	return {
		severity: registryEntry.defaultSeverity,
		code: 'SKILL_DESCRIPTION_WRONG_PERSON',
		message: `Description uses first-person or conversational second-person voice ("${match[0]}") — Anthropic recommends third person`,
		field: FRONTMATTER_DESC_FIELD,
		fix: registryEntry.fix,
		reference: registryEntry.reference,
	};
}
