/**
 * Shared frontmatter validation logic
 *
 * Validates skill frontmatter (name format, description, reserved words, etc.)
 * Used by both validateSkill() and validateSkillForPackaging() to ensure
 * consistent validation regardless of entry point.
 */

import { AgentSkillFrontmatterSchema, VATAgentSkillFrontmatterSchema } from '../schemas/agent-skill-frontmatter.js';

import type { ValidationIssue } from './types.js';

// Location constants for validation messages
const FRONTMATTER_LOC = 'frontmatter';
const FRONTMATTER_NAME_LOC = 'frontmatter.name';
const FRONTMATTER_DESC_LOC = 'frontmatter.description';

/**
 * Validate frontmatter against the Agent Skill schema
 *
 * Checks name format (regex), description length, required fields, etc.
 *
 * @param frontmatter - Parsed frontmatter key-value pairs
 * @param isVATGenerated - Whether skill was generated by VAT (stricter schema)
 * @returns Array of validation issues found
 */
export function validateFrontmatterSchema(
	frontmatter: Record<string, unknown>,
	isVATGenerated: boolean,
): ValidationIssue[] {
	const issues: ValidationIssue[] = [];
	const schema = isVATGenerated ? VATAgentSkillFrontmatterSchema : AgentSkillFrontmatterSchema;
	const schemaResult = schema.safeParse(frontmatter);

	if (schemaResult.success) {
		return issues;
	}

	// Map Zod errors to our issue codes
	for (const error of schemaResult.error.errors) {
		const field = error.path.join('.');

		if (field === 'name' && !frontmatter['name']) {
			issues.push({
				severity: 'error',
				code: 'SKILL_MISSING_NAME',
				message: 'Required field "name" is missing',
				location: FRONTMATTER_LOC,
				fix: 'Add "name" field to frontmatter',
			});
		} else if (field === 'description' && !frontmatter['description']) {
			issues.push({
				severity: 'error',
				code: 'SKILL_MISSING_DESCRIPTION',
				message: 'Required field "description" is missing',
				location: FRONTMATTER_LOC,
				fix: 'Add "description" field to frontmatter',
			});
		} else if (field === 'name') {
			issues.push({
				severity: 'error',
				code: 'SKILL_NAME_INVALID',
				message: error.message,
				location: FRONTMATTER_NAME_LOC,
				fix: 'Change name to lowercase alphanumeric with hyphens (e.g., "my-skill")',
			});
		} else if (field === 'description' && error.message.includes('1024')) {
			issues.push({
				severity: 'error',
				code: 'SKILL_DESCRIPTION_TOO_LONG',
				message: `Description exceeds 1024 characters (actual: ${(frontmatter['description'] as string)?.length ?? 0})`,
				location: FRONTMATTER_DESC_LOC,
				fix: 'Reduce description to 1024 characters or less',
			});
		}
	}

	return issues;
}

/**
 * Validate additional frontmatter rules beyond schema
 *
 * Checks reserved words, XML tags, empty descriptions, etc.
 *
 * @param frontmatter - Parsed frontmatter key-value pairs
 * @returns Array of validation issues found
 */
export function validateFrontmatterRules(
	frontmatter: Record<string, unknown>,
): ValidationIssue[] {
	const issues: ValidationIssue[] = [];

	// Validate name field
	if (frontmatter['name'] && typeof frontmatter['name'] === 'string') {
		const name = frontmatter['name'].toLowerCase();

		// Check for reserved words
		if (name.includes('anthropic') || name.includes('claude')) {
			issues.push({
				severity: 'error',
				code: 'SKILL_NAME_RESERVED_WORD',
				message: 'Name contains reserved word "anthropic" or "claude"',
				location: FRONTMATTER_NAME_LOC,
				fix: 'Remove reserved word from name',
			});
		}

		// Check for XML tags
		if (/[<>]/.test(frontmatter['name'])) {
			issues.push({
				severity: 'error',
				code: 'SKILL_NAME_XML_TAGS',
				message: 'Name contains XML tags',
				location: FRONTMATTER_NAME_LOC,
				fix: 'Remove < and > characters from name',
			});
		}
	}

	// Validate description field
	if (frontmatter['description'] && typeof frontmatter['description'] === 'string') {
		// Check for XML tags
		if (/[<>]/.test(frontmatter['description'])) {
			issues.push({
				severity: 'error',
				code: 'SKILL_DESCRIPTION_XML_TAGS',
				message: 'Description contains XML tags',
				location: FRONTMATTER_DESC_LOC,
				fix: 'Remove < and > characters from description',
			});
		}

		// Check for empty description
		if (frontmatter['description'].trim() === '') {
			issues.push({
				severity: 'error',
				code: 'SKILL_DESCRIPTION_EMPTY',
				message: 'Description is empty',
				location: FRONTMATTER_DESC_LOC,
				fix: 'Add description explaining what the skill does and when to use it',
			});
		}
	}

	return issues;
}
