/**
 * The `.` barrel's runtime export set — a ratchet, both ways. How to react when
 * this fails is written on `findBarrelDrift` in
 * `packages/dev-tools/src/pin-barrel-exports.ts`; in one line: a removal is a
 * breaking change (restore it, or record it in CHANGELOG.md), an addition is
 * deliberate and needs a consumer outside this package before it is added here.
 */

import { describe, expect, it } from 'vitest';

import { findBarrelDrift } from '../../dev-tools/src/pin-barrel-exports.js';

// This list and `subpath-purity.test.ts`'s `index.ts` row are two halves of one
// rule: a module that brings a third-party dependency — directly, or
// transitively through anything it imports — belongs on a subpath. Adding such
// a name here reddens the purity row, and the fix is a subpath entry, not a
// longer list. Names whose modules reach only `node:*` are the ones this list
// is for. Test scaffolding (the temp-dir suite family, the fs-refusal fakes,
// the crawl-timing `__*ForTest` seams) is on `./testing`, never here.
const BARREL_EXPORTS = [
  'ASSET_REFERENCE_UNREADABLE_CODE',
  'ASSET_REFERENCE_UNRESOLVED_CODE',
  'COPY_LINK_ESCAPES_SOURCE_CODE',
  'CRAWL_BLOB_POPULATE_ID',
  'CRAWL_CLOSURE_CONTRIBUTE_ID',
  'CRAWL_CLOSURE_RESOLVE_ID',
  'CRAWL_PASS_INSIDE',
  'CRAWL_REGISTRY_ADMIT_ID',
  'CRAWL_REGISTRY_ENUMERATE_ID',
  'CRAWL_REGISTRY_ID_PREFIX',
  'CRAWL_REGISTRY_RESOLVE_LINKS_ID',
  'CRAWL_SHARED_GIT_TRACKER_ID',
  'CRAWL_STORE_READ_ID',
  'CRAWL_STORE_WRITE_ID',
  'CRAWL_STRATA',
  'CRAWL_WALKER_GITIGNORE_ID',
  'CRAWL_WALKER_ID',
  'CopyLinkEscapesSourceError',
  'DIRECTORY_WALK_REVISITED_CODE',
  'DirectorySpellingIndex',
  'DirectoryWalkRevisitedError',
  'FS_CONCURRENCY',
  'FS_FAULT_CODE',
  'FS_FAULT_ERRNOS_BY_CLASS',
  'FS_SIDES',
  'FollowedWalk',
  'FsFaultError',
  'FsLookupCache',
  'INHERITED_GIT_ENV',
  'MAX_DECODABLE_BYTES',
  'PathEscapesRootError',
  'RAG_DATABASE_UNREADABLE_CODE',
  'RAG_INDEX_EMPTY_CODE',
  'SKILL_SCOPE_NAMES',
  'SKILL_TARGETS',
  'SKILL_TARGET_NAMES',
  'SOURCE_ORIGINS',
  'TEMP_DIR_OUTSIDE_TMPDIR_CODE',
  'TEST_USER_STATE_UNDER',
  'TREE_CLEANUP_INCOMPLETE_CODE',
  'TREE_DESTS_OVERLAP_CODE',
  'TREE_DEST_HOLDS_SOURCE_CODE',
  'TREE_DEST_NOT_OWNED_CODE',
  'TREE_DEST_OCCUPIED_CODE',
  'TREE_ROLLBACK_INCOMPLETE_CODE',
  'TREE_SOURCE_HOLDS_DEST_CODE',
  'TextTooLargeError',
  'TreeRollbackIncompleteError',
  'VatError',
  'ZodTypeNames',
  'applyTreePlan',
  'applyTreePlanOrLeftover',
  'canonicalPath',
  'classifyFsFault',
  'compareCodeUnits',
  'copyRegularFile',
  'copyTree',
  'crawlTimingStart',
  'createSymlink',
  'createSymlinkAsync',
  'decodeTextContent',
  'detachGitEnv',
  'direntKind',
  'direntKindFollowing',
  'direntKindFollowingSync',
  'disposeTempDir',
  'disposeTempDirAfterFailure',
  'dynamicImportPath',
  'ensureTimingDirectory',
  'entryIdentities',
  'errnoError',
  'everyInOrder',
  'exceedsDecodableLength',
  'fileContentHash',
  'fillPathSpellings',
  'fillRealpaths',
  'findConfigFile',
  'findNodeWorkspaceRoot',
  'findProjectRoot',
  'forEachInOrder',
  'fsBoundary',
  'fsFaultOf',
  'getRelativePath',
  'getZodTypeName',
  'globMagicRemainder',
  'hasParentTraversalSegment',
  'isAbsoluteAnyPlatform',
  'isAbsolutePath',
  'isAlreadyExistsError',
  'isCapacityFault',
  'isFileInTheWayError',
  'isFsFaultError',
  'isGlob',
  'isInsideByIdentity',
  'isInvalidArgumentError',
  'isLayoutFault',
  'isLinkLoopError',
  'isNoSuchEntryError',
  'isNotARegularFileError',
  'isParkedTreeEntry',
  'isPathAbsentError',
  'isProcessGoneError',
  'isRenameContentionError',
  'isSingleFsSegment',
  'isSymlinkUnsupportedError',
  'isTimedOutError',
  'isTreeChangeResidue',
  'isUnderRoot',
  'isVatError',
  'isWouldBlockError',
  'isZodNullable',
  'isZodOptional',
  'isZodType',
  'issueLocation',
  'makeDirectoryUnder',
  'mapConcurrentFailingInOrder',
  'mapInOrder',
  'mapWithConcurrency',
  'mkdirSyncReal',
  'normalizePath',
  'normalizeTimingDirectory',
  'normalizedTmpdir',
  'openForReading',
  'parseEnvBoolean',
  'parseWholeNumberAtLeast',
  'pathPresent',
  'pathSpellingFrom',
  'planTreeChanges',
  'prefixMessageOnce',
  'promised',
  'proveTreeReadable',
  'readDecodableBytes',
  'readRegularFile',
  'readTextContent',
  'readTextContentSync',
  'readTimingProcess',
  'realpathFrom',
  'recordContributorInvocation',
  'recordCrawlPass',
  'recordRegistryPass',
  'recordSharedPass',
  'recordSuppressedFault',
  'relativeEscapesRoot',
  'renameFileAtomic',
  'replaceFile',
  'requireConfirmedAbsent',
  'requireTestScratch',
  'resetProjectRootCaches',
  'resolveAssetReference',
  'resolveFromImportMeta',
  'resolveSkillTarget',
  'safePath',
  'sameEntry',
  'spellingWalkRoot',
  'staticGlobBase',
  'suppressedFaultsOf',
  'symlinkCapability',
  'toAbsolutePath',
  'toForwardSlash',
  'toForwardSlashAnyPlatform',
  'toNfc',
  'transientRefusalClause',
  'unwrapZodType',
  'withContributorStratum',
  'withFsFault',
  'withFsFaultSync',
  'withOuterBracket',
  'withTempDir',
  'writeFileUnder',
  'writeTimingDump',
];

describe('@vibe-agent-toolkit/utils — the `.` barrel export surface', () => {
  it('exports exactly the recorded set, sorted — nothing added, dropped, or out of order', async () => {
    expect(findBarrelDrift(await import('../src/index.js'), BARREL_EXPORTS)).toEqual({ added: [], removed: [], unsorted: [] });
  });
});
