/**
 * The `.` barrel's runtime export set — a ratchet, both ways. How to react when
 * this fails is written on `findBarrelDrift` in
 * `packages/dev-tools/src/pin-barrel-exports.ts`; in one line: a removal is a
 * breaking change (restore it, or record it in CHANGELOG.md), an addition is
 * deliberate and needs a consumer outside this package before it is added here.
 */

import { describe, expect, it } from 'vitest';

import { findBarrelDrift } from '../../dev-tools/src/pin-barrel-exports.js';

const BARREL_EXPORTS = [
  'API_REQUEST_CODE',
  'API_TRANSPORT_CODE',
  'ApiRequestError',
  'ApiTransportError',
  'CLAUDE_USER_STATE_UNREADABLE_CODE',
  'CLAUDE_USER_STATE_WRITE_FAILED_CODE',
  'ClaudeAuthConfigSchema',
  'ClaudeInstallInventory',
  'ClaudeMarketplaceInventory',
  'ClaudeModelConfigSchema',
  'ClaudePluginInventory',
  'ClaudePluginJsonSchema',
  'ClaudePluginSchema',
  'ClaudeSkillInventory',
  'HooksConfigSchema',
  'INVENTORY_CRAWL_ENV',
  'INVENTORY_CRAWL_PROJECTION',
  'INVENTORY_CRAWL_WALKER',
  'INVENTORY_EXTENT_CONTRIBUTOR_ID_PREFIX',
  'INVENTORY_EXTENT_KIND',
  'INVENTORY_MAX_DEPTH',
  'INVENTORY_REFUSED_AGENT_INSTRUCTION_FILE',
  'INVENTORY_REFUSED_DIRECTORY_TARGET',
  'INVENTORY_REFUSED_GITIGNORED',
  'INVENTORY_REFUSED_NAVIGATION_FILE',
  'InventorySkillExtentContributor',
  'MANIFEST_UNREADABLE',
  'MARKETPLACE_CONTRIBUTOR_ID',
  'MARKETPLACE_KIND',
  'ManagedSettingsSchema',
  'MarketplaceExtentContributor',
  'MarketplaceSourceSchema',
  'McpServerPolicySchema',
  'NO_GIT_TRACKER',
  'ORG_API_KEY_MISSING_CODE',
  'OrgApiClient',
  'PLUGIN_CONTRIBUTOR_ID',
  'PLUGIN_KEY_INVALID_CODE',
  'PLUGIN_KIND',
  'PLUGIN_NOT_INSTALLED',
  'PLUGIN_SOURCE_UNREADABLE_CODE',
  'PermissionsConfigSchema',
  'PluginExtentContributor',
  'ProjectSettingsSchema',
  'SandboxConfigSchema',
  'SandboxFilesystemSchema',
  'SandboxNetworkSchema',
  'UserSettingsSchema',
  'WINDOWS_LEGACY_MANAGED_SETTINGS_PATH',
  'analyzeCompatibility',
  'analyzeRuleConflicts',
  'auditSettings',
  'buildClaudeUserPaths',
  'buildInventoryPopulation',
  'buildMultipartFormData',
  'checkSettingsCompatibility',
  'codedUserStateWrite',
  'computeVerdicts',
  'crawlSkillLinkRegistry',
  'createOrgApiClientFromEnv',
  'detectSkillClaudePluginNameMismatch',
  'extractClaudeInstallInventory',
  'extractClaudeMarketplaceInventory',
  'extractClaudePluginInventory',
  'extractClaudeSkillInventory',
  'findPluginsByPackage',
  'getClaudeProjectPaths',
  'getClaudeUserPaths',
  'getManagedSettingsCandidatePaths',
  'getSettingsFileFields',
  'getSettingsPaths',
  'installPlugin',
  'inventoryExtentContributorId',
  'inventoryExtentDeclaration',
  'inventoryExtentName',
  'isSubsumedBy',
  'listLocalPlugins',
  'matchesAllowRule',
  'matchesBashRule',
  'matchesDenyRule',
  'matchesPathRule',
  'matchesPermissionRule',
  'mergeSettingsLayers',
  'parsePluginKey',
  'probePathAccess',
  'projectionCrawlSelected',
  'readEffectiveSettings',
  'readInstalledPlugins',
  'readKnownMarketplaces',
  'readMarketplaceDefaultTargets',
  'readSettingsLayers',
  'requirePluginInstallNames',
  'resolveEffectiveTargets',
  'resolveSettingsPaths',
  'skillVersionsPath',
  'uninstallPlugin',
  'validatePlugin',
  'validateSettingsFile',
  'writeInstalledPlugins',
  'writeKnownMarketplaces',
];

describe('@vibe-agent-toolkit/claude-marketplace — the `.` barrel export surface', () => {
  it('exports exactly the recorded set, sorted — nothing added, dropped, or out of order', async () => {
    expect(findBarrelDrift(await import('../src/index.js'), BARREL_EXPORTS)).toEqual({ added: [], removed: [], unsorted: [] });
  });
});
