#!/usr/bin/env tsx
/**
 * Generate `.github/workflows/validate.yml` from `vibe-validate.config.yaml`.
 *
 * The file used to carry a "THIS FILE IS AUTO-GENERATED by vibe-validate
 * generate-workflow — DO NOT EDIT MANUALLY" banner while being hand-edited
 * underneath it: `vibe-validate generate-workflow --check` had been failing for
 * months, and regenerating with it would have DELETED the contraband-token step
 * (the adopter-name gate's secret) and downgraded two actions. Nothing ran the
 * check, so the banner was a claim, not a mechanism.
 *
 * vibe-validate's generator cannot express what this repo's CI needs — a
 * SHA-pinned setup-bun, a frozen install, Node read from `engines`, one
 * composite setup action shared by every workflow — so the generator is this
 * file, and the banner now names it. What vibe-validate DOES own is the matrix:
 * `ci.nodeVersions`, `ci.os` and `ci.failFast` are read from its config here,
 * so the local gate and the CI matrix keep one source.
 *
 * Usage:
 *   bun run --cwd packages/dev-tools generate:workflow           # rewrite validate.yml
 *   bun run --cwd packages/dev-tools generate:workflow --check   # exit 1 if validate.yml is stale
 *
 * `--check` runs inside `validate-structure`.
 */

import { readFileSync, writeFileSync } from 'node:fs';

import { ExitCode, type ExitCodeValue } from '@vibe-agent-toolkit/schema';
import { isPathAbsentError, safePath } from '@vibe-agent-toolkit/utils';
import { parse as parseYaml } from 'yaml';

import { isEntrypoint, log, PROJECT_ROOT } from './common.js';

export const WORKFLOW_PATH = '.github/workflows/validate.yml';
const CONFIG_PATH = 'vibe-validate.config.yaml';

/** The matrix vibe-validate's config declares. */
export interface CiMatrix {
  readonly nodeVersions: readonly string[];
  readonly os: readonly string[];
  readonly failFast: boolean;
}

/**
 * Read the CI matrix from `vibe-validate.config.yaml`.
 *
 * @throws When the `ci:` block is absent or names no Node version — a matrix
 *   with nothing in it is not a default this file should invent
 */
export function readCiMatrix(repoRoot: string): CiMatrix {
  const raw = parseYaml(readFileSync(safePath.join(repoRoot, CONFIG_PATH), 'utf8')) as {
    ci?: { nodeVersions?: unknown; os?: unknown; failFast?: unknown };
  } | null;
  const ci = raw?.ci;
  const nodeVersions = Array.isArray(ci?.nodeVersions) ? ci.nodeVersions.map(String) : [];
  const os = Array.isArray(ci?.os) ? ci.os.map(String) : [];
  if (nodeVersions.length === 0 || os.length === 0) {
    throw new Error(`${CONFIG_PATH} must declare ci.nodeVersions and ci.os; the workflow matrix is read from there`);
  }
  return { nodeVersions, os, failFast: ci?.failFast === true };
}

const yamlList = (items: readonly string[], indent: string): string =>
  items.map((item) => `${indent}- ${JSON.stringify(item)}`).join('\n');

/**
 * The workflow text for a matrix.
 *
 * Every step is spelled here, comments included, so the generated file reads
 * as the hand-written one did. A step that must survive regeneration — the
 * contraband token provisioning — lives HERE, which is the property the old
 * banner promised and did not have.
 */
export function renderValidateWorkflow(matrix: CiMatrix): string {
  return `# THIS FILE IS GENERATED by \`bun run --cwd packages/dev-tools generate:workflow\` (packages/dev-tools/src/generate-workflow.ts).
# DO NOT EDIT BY HAND — \`validate-structure\` fails when this file differs from what the
# generator produces. The matrix comes from vibe-validate.config.yaml (ci.nodeVersions,
# ci.os, ci.failFast); the toolchain steps come from .github/actions/setup.
name: Validation Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  validate:
    name: Run vibe-validate validation
    runs-on: \${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      # The matrix Node version, not the floor: this job is the broad validation
      # run, and node-floor.yml is the one that executes the declared floor.
      - name: Setup toolchain
        uses: ./.github/actions/setup
        with:
          node-version: \${{ matrix.node }}
      # The adopter-name gate reads its token list from outside the repo, because a
      # contraband list committed to a public repo is itself the leak. Materialize it
      # from a repo secret into the gitignored default path the gate already looks for.
      #
      # When the secret is absent (a fork, or before it is configured) no file is written
      # and the gate reports that it did NOT run — it never silently reports success. The
      # emptiness test is done in the shell rather than an \`if:\` expression because the
      # \`secrets\` context is not dependable in step-level conditionals.
      - name: Provision contraband token list
        shell: bash
        run: |
          if [ -n "$CONTRABAND_TOKENS" ]; then
            printf '%s\\n' "$CONTRABAND_TOKENS" > .contraband-tokens
            echo "Provisioned contraband token list for the adopter-name gate."
          else
            echo "::warning::CONTRABAND_TOKENS secret is not set - the adopter-name gate will not run."
          fi
        env:
          CONTRABAND_TOKENS: \${{ secrets.CONTRABAND_TOKENS }}
      # NET_AVAILABLE: the four network suites (external-link-validator,
      # external-url-validation, audit-git-url, corpus-scan) skip unless it is
      # set; a hosted runner has the network, so this is the tier that runs them.
      # Locally they stay opt-in (\`NET_AVAILABLE=1 bun run validate\`).
      - name: Run validation
        run: bun run validate
        env:
          GH_TOKEN: \${{ github.token }}
          NET_AVAILABLE: "1"
      # vibe-validate captures a failed step's stdout and stderr to files and summarises
      # them through an extractor that keeps only lines carrying an error keyword, so a
      # verdict without one (\`NEW unused export: …\`) never reaches this log. Print the
      # captures verbatim: the step's own words are the record, not the summary.
      - name: Print failed step output
        if: failure()
        run: bun run print-failed-step-output
    strategy:
      fail-fast: ${matrix.failFast ? 'true' : 'false'}
      matrix:
        os:
${yamlList(matrix.os, '          ')}
        node:
${yamlList(matrix.nodeVersions, '          ')}
  all-validation-passed:
    name: All Validation Passed
    runs-on: ubuntu-latest
    needs:
      - validate
    if: always()
    steps:
      - name: Check all validation jobs
        run: |-
          if [ "\${{ needs.validate.result }}" != "success" ]; then
            echo "❌ Some validation checks failed"
            exit 1
          fi
          echo "✅ All validation checks passed!"
`;
}

/** The workflow text the tree should hold right now. */
export function expectedValidateWorkflow(repoRoot: string): string {
  return renderValidateWorkflow(readCiMatrix(repoRoot));
}

/** Whether the committed workflow matches the generator, with the expected text. */
export function checkValidateWorkflow(repoRoot: string): { inSync: boolean; expected: string } {
  const expected = expectedValidateWorkflow(repoRoot);
  let current = '';
  try {
    current = readFileSync(safePath.join(repoRoot, WORKFLOW_PATH), 'utf8');
  } catch (error) {
    // An absent file is out of sync by definition; anything else is a real failure.
    if (isPathAbsentError(error)) return { inSync: false, expected };
    throw error;
  }
  return { inSync: current.replaceAll('\r\n', '\n') === expected, expected };
}

function main(argv: readonly string[]): ExitCodeValue {
  const check = argv.includes('--check');
  const { inSync, expected } = checkValidateWorkflow(PROJECT_ROOT);
  if (inSync) {
    log(`✓ ${WORKFLOW_PATH} matches vibe-validate.config.yaml`, 'green');
    return ExitCode.OK;
  }
  if (check) {
    log(`✗ ${WORKFLOW_PATH} differs from what the generator produces`, 'red');
    log('  Regenerate with: bun run --cwd packages/dev-tools generate:workflow', 'yellow');
    return ExitCode.FINDINGS;
  }
  writeFileSync(safePath.join(PROJECT_ROOT, WORKFLOW_PATH), expected, 'utf8');
  log(`✓ Regenerated ${WORKFLOW_PATH}`, 'green');
  return ExitCode.OK;
}

if (isEntrypoint(import.meta.url)) {
  process.exit(main(process.argv.slice(2)));
}
