/**
 * The unused-export ratchet: every `export` knip reports as referenced by
 * nothing in the project graph, excused by name. Read by
 * `packages/dev-tools/src/unused-exports.ts` (`bun run unused-exports`).
 *
 * The list may only SHRINK. `reason` is `test-only` (a test reaches the
 * name — the export exists for that test) or `dead` (nothing does). Both are
 * read off `packages/<pkg>/test/` — an import of the module plus a whole-
 * identifier mention of the name — a hint and not a proof.
 *
 * Generated by `bun run unused-exports --seed`; entries leave by hand or by
 * `--prune`. Never add one by hand: an unused export is fixed at the export.
 */

export type UnusedExportReason = 'test-only' | 'dead';

export interface UnusedExportName {
  readonly name: string;
  readonly reason: UnusedExportReason;
}

export interface UnusedExportFile {
  /** Repo-relative, forward-slash path of the module. */
  readonly file: string;
  readonly unused: readonly UnusedExportName[];
}

export const UNUSED_EXPORTS_ALLOWLIST: readonly UnusedExportFile[] = [
  { file: 'packages/agent-runtime/src/execute-wrapper.ts', unused: [
    { name: 'ExecuteWrapperConfig', reason: 'dead' },
  ] },
  { file: 'packages/agent-runtime/src/session/test-helpers/index.ts', unused: [
    { name: 'testDeleteMethod', reason: 'dead' },
    { name: 'testExistsMethod', reason: 'dead' },
    { name: 'testListMethod', reason: 'dead' },
  ] },
  { file: 'packages/agent-runtime/src/shared-validation.ts', unused: [
    { name: 'createValidatedExecute', reason: 'dead' },
  ] },
  { file: 'packages/agent-skills/src/evidence/index.ts', unused: [
    { name: 'detectInterpreter', reason: 'dead' },
    { name: 'extractMcpCommandFromMatchText', reason: 'dead' },
  ] },
  { file: 'packages/agent-skills/src/fs-attribution.ts', unused: [
    { name: 'WRITE_REMEDY', reason: 'dead' },
  ] },
  { file: 'packages/agent-skills/src/inventory/serialize.ts', unused: [
    { name: 'ShallowInventory', reason: 'dead' },
  ] },
  { file: 'packages/agent-skills/src/schemas/installed-plugins-registry.ts', unused: [
    { name: 'InstalledPluginsRegistry', reason: 'dead' },
    { name: 'InstalledPluginsRegistryJsonSchema', reason: 'dead' },
    { name: 'KNOWN_INSTALLATION_SCOPES', reason: 'dead' },
    { name: 'PluginInstallation', reason: 'dead' },
  ] },
  { file: 'packages/agent-skills/src/schemas/known-marketplaces-registry.ts', unused: [
    { name: 'KNOWN_MARKETPLACE_SOURCE_KINDS', reason: 'dead' },
    { name: 'KnownMarketplacesRegistryJsonSchema', reason: 'dead' },
    { name: 'MarketplaceEntry', reason: 'dead' },
    { name: 'MarketplaceSource', reason: 'dead' },
  ] },
  { file: 'packages/agent-skills/src/skill-source/fetch-cache.ts', unused: [
    { name: 'CachedFetchArgs', reason: 'dead' },
  ] },
  { file: 'packages/agent-skills/src/skill-source/sources/workspace-source.ts', unused: [
    { name: 'WorkspaceResolveOptions', reason: 'dead' },
  ] },
  { file: 'packages/agent-skills/src/skill-source/stage.ts', unused: [
    { name: 'StageOptions', reason: 'dead' },
  ] },
  { file: 'packages/agent-skills/src/skill-test/baseline-delta.ts', unused: [
    { name: 'ComputeBaselineDeltaInput', reason: 'dead' },
    { name: 'EvalDelta', reason: 'dead' },
    { name: 'EvalDeltaSchema', reason: 'dead' },
  ] },
  { file: 'packages/agent-skills/src/skill-test/baseline-integrity.ts', unused: [
    { name: 'BASELINE_SCAN_DEGRADATION_REASONS', reason: 'dead' },
    { name: 'PathNeedle', reason: 'dead' },
    { name: 'ToolIntent', reason: 'dead' },
  ] },
  { file: 'packages/agent-skills/src/skill-test/eval-inputs.ts', unused: [
    { name: 'armsOf', reason: 'dead' },
  ] },
  { file: 'packages/agent-skills/src/skill-test/lock.ts', unused: [
    { name: 'InstallSignalCleanupOptions', reason: 'dead' },
  ] },
  { file: 'packages/agent-skills/src/skill-test/run-harness.ts', unused: [
    { name: 'ArtifactPaths', reason: 'dead' },
    { name: 'CleanupHarnessOptions', reason: 'dead' },
    { name: 'EvalWorkItem', reason: 'dead' },
    { name: 'RunCostSummary', reason: 'dead' },
  ] },
  { file: 'packages/agent-skills/src/skill-test/tier-plan.ts', unused: [
    { name: 'DEFAULT_TIER', reason: 'dead' },
  ] },
  { file: 'packages/agent-skills/src/skill-test/vendor-manifest.ts', unused: [
    { name: 'VendoredManifest', reason: 'dead' },
  ] },
  { file: 'packages/agent-skills/src/test-input.ts', unused: [
    { name: 'ExcludedLinkRef', reason: 'dead' },
  ] },
  { file: 'packages/agent-skills/src/validators/compat-detectors.ts', unused: [
    { name: 'collectBrowserAuthEvidence', reason: 'dead' },
    { name: 'collectExternalCLIEvidence', reason: 'dead' },
    { name: 'collectLocalShellEvidence', reason: 'dead' },
  ] },
  { file: 'packages/agent-skills/src/validators/description-style-detection.ts', unused: [
    { name: 'DescriptionStyleInput', reason: 'dead' },
    { name: 'DescriptionYamlStyle', reason: 'dead' },
  ] },
  { file: 'packages/agent-skills/src/validators/packaged-size-limit.ts', unused: [
    { name: 'BundleWalk', reason: 'dead' },
    { name: 'OversizeMeasure', reason: 'dead' },
    { name: 'UnweighedEntry', reason: 'dead' },
  ] },
  { file: 'packages/agent-skills/src/validators/rule-engine/index.ts', unused: [
    { name: 'FileCopyRole', reason: 'dead' },
    { name: 'FileKind', reason: 'dead' },
    { name: 'ReferencedHow', reason: 'dead' },
    { name: 'RulePhase', reason: 'dead' },
    { name: 'RuleScope', reason: 'dead' },
    { name: 'RuleSubject', reason: 'dead' },
  ] },
  { file: 'packages/agent-skills/src/validators/skill-validator.ts', unused: [
    { name: 'ImplicitReference', reason: 'dead' },
  ] },
  { file: 'packages/claude-marketplace/src/org/org-api-client.ts', unused: [
    { name: 'ApiResponseOutcome', reason: 'dead' },
    { name: 'isRetryableTransportFailure', reason: 'dead' },
    { name: 'RetryDecision', reason: 'dead' },
  ] },
  { file: 'packages/claude-marketplace/src/runtime-profiles.ts', unused: [
    { name: 'CapabilityYesNo', reason: 'dead' },
    { name: 'NetworkLevel', reason: 'dead' },
    { name: 'RuntimeProfile', reason: 'dead' },
  ] },
  { file: 'packages/claude-marketplace/src/scanners/command-classifier.ts', unused: [
    { name: 'classifyCommandBinary', reason: 'dead' },
    { name: 'COMMAND_RULES', reason: 'dead' },
    { name: 'CommandRule', reason: 'dead' },
  ] },
  { file: 'packages/claude-marketplace/src/scanners/index.ts', unused: [
    { name: 'classifyCommand', reason: 'dead' },
    { name: 'classifyCommandBinary', reason: 'dead' },
    { name: 'COMMAND_RULES', reason: 'dead' },
    { name: 'PYTHON_STDLIB_MODULES', reason: 'dead' },
  ] },
  { file: 'packages/claude-marketplace/src/schemas/index.ts', unused: [
    { name: 'MarketplaceSource', reason: 'dead' },
  ] },
  { file: 'packages/claude-marketplace/src/schemas/permissions.ts', unused: [
    { name: 'PermissionRuleSchema', reason: 'dead' },
  ] },
  { file: 'packages/claude-marketplace/src/settings/path-pattern.ts', unused: [
    { name: 'PathPattern', reason: 'dead' },
  ] },
  { file: 'packages/claude-marketplace/src/settings/permission-matcher.ts', unused: [
    { name: 'ruleConstrainsTool', reason: 'dead' },
  ] },
  { file: 'packages/claude-marketplace/src/settings/settings-auditor.ts', unused: [
    { name: 'ReadSettingsOptions', reason: 'dead' },
  ] },
  { file: 'packages/claude-marketplace/src/settings/settings-compat-checker.ts', unused: [
    { name: 'SettingsCheck', reason: 'dead' },
    { name: 'SettingsUnchecked', reason: 'dead' },
  ] },
  { file: 'packages/claude-marketplace/src/settings/settings-reader.ts', unused: [
    { name: 'EffectiveSettings', reason: 'dead' },
    { name: 'SettingsLayer', reason: 'dead' },
  ] },
  { file: 'packages/claude-marketplace/src/walk-following-links.ts', unused: [
    { name: 'WalkOptions', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/agent/build.ts', unused: [
    { name: 'BuildCommandOptions', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/agent/import.ts', unused: [
    { name: 'ImportCommandOptions', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/agent/install.ts', unused: [
    { name: 'InstallOptions', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/agent/installed.ts', unused: [
    { name: 'InstalledCommandOptions', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/agent/list.ts', unused: [
    { name: 'ListCommandOptions', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/agent/run.ts', unused: [
    { name: 'RunCommandOptions', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/agent/uninstall.ts', unused: [
    { name: 'UninstallOptions', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/agent/validate.ts', unused: [
    { name: 'ValidateCommandOptions', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/ard/emit.ts', unused: [
    { name: 'ARD_EMIT_CODES', reason: 'dead' },
    { name: 'ArdConfigAbsence', reason: 'dead' },
    { name: 'ArdEmitData', reason: 'dead' },
    { name: 'ArdEmitDataSchema', reason: 'dead' },
    { name: 'ArdEmitReport', reason: 'dead' },
    { name: 'ArdEmitResult', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/ard/index.ts', unused: [
    { name: 'ArdConfigMissingError', reason: 'test-only' },
    { name: 'ardEmitCommand', reason: 'test-only' },
    { name: 'ArdEmitReport', reason: 'dead' },
    { name: 'ArdSurfaceCollection', reason: 'dead' },
    { name: 'buildArdEmitReport', reason: 'dead' },
    { name: 'collectArdSurfaces', reason: 'test-only' },
    { name: 'DEFAULT_ARD_OUTPUT', reason: 'dead' },
    { name: 'runArdEmit', reason: 'test-only' },
    { name: 'SkippedArdSurface', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/ard/surfaces.ts', unused: [
    { name: 'ArdSurfaceCollection', reason: 'dead' },
    { name: 'ArdSurfaceDefaults', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/audit-settings.ts', unused: [
    { name: 'AuditSettingsOptions', reason: 'dead' },
    { name: 'FormattedProvenanceValue', reason: 'dead' },
    { name: 'runAuditSettings', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/audit.ts', unused: [
    { name: 'auditCommand', reason: 'test-only' },
  ] },
  { file: 'packages/cli/src/commands/audit/cache-detector.ts', unused: [
    { name: 'CacheStalenessResult', reason: 'dead' },
    { name: 'FreshEntry', reason: 'dead' },
    { name: 'StaleEntry', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/audit/distributed-tree.ts', unused: [
    { name: 'SkillTreeProvenance', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/audit/git-url-clone.ts', unused: [
    { name: 'CloneAndAuditContext', reason: 'dead' },
    { name: 'CloneOptions', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/audit/hierarchical-output.ts', unused: [
    { name: 'CacheStatus', reason: 'dead' },
    { name: 'HierarchicalOutput', reason: 'dead' },
    { name: 'MarketplaceGroup', reason: 'dead' },
    { name: 'PluginGroup', reason: 'dead' },
    { name: 'SkillEntry', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/audit/scan-population.ts', unused: [
    { name: 'AuditScanOptions', reason: 'dead' },
    { name: 'AuditScanPopulation', reason: 'dead' },
    { name: 'ScanLogger', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/build.ts', unused: [
    { name: 'BuildCommandOptions', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/cache/cache-control.ts', unused: [
    { name: 'CacheControlOptions', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/cache/clear.ts', unused: [
    { name: 'CacheClearReport', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/claude/budget.ts', unused: [
    { name: 'BudgetDataSchema', reason: 'dead' },
    { name: 'BudgetOutputFormat', reason: 'dead' },
    { name: 'ClaudeBudgetOptions', reason: 'dead' },
    { name: 'ReportInput', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/claude/claude-config.ts', unused: [
    { name: 'LoadedClaudeConfig', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/claude/context.ts', unused: [
    { name: 'ClaudeContextOptions', reason: 'dead' },
    { name: 'ContextCostMapEnvelope', reason: 'dead' },
    { name: 'ContextEnvelope', reason: 'dead' },
    { name: 'ContextOutputFormat', reason: 'dead' },
    { name: 'ContextUnknownDocument', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/claude/marketplace/git-publish.ts', unused: [
    { name: 'CommitMetadata', reason: 'dead' },
    { name: 'PublishGitOptions', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/claude/marketplace/license-utils.ts', unused: [
    { name: 'resolveLicense', reason: 'test-only' },
  ] },
  { file: 'packages/cli/src/commands/claude/marketplace/publish-tree.ts', unused: [
    { name: 'ComposeResult', reason: 'test-only' },
  ] },
  { file: 'packages/cli/src/commands/claude/marketplace/publish.ts', unused: [
    { name: 'MarketplacePublishOptions', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/claude/marketplace/validate.ts', unused: [
    { name: 'LocationIssueSummary', reason: 'dead' },
    { name: 'MarketplaceFindings', reason: 'dead' },
    { name: 'MarketplaceValidateReport', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/claude/org/helpers.ts', unused: [
    { name: 'autopaginateCustom', reason: 'dead' },
    { name: 'OrgCommandEnding', reason: 'dead' },
    { name: 'QueryParams', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/claude/org/skills.ts', unused: [
    { name: 'HalfDeletedReport', reason: 'dead' },
    { name: 'NpmInstallSummary', reason: 'dead' },
    { name: 'SkillDeleteResult', reason: 'dead' },
    { name: 'SkillUploadFailure', reason: 'dead' },
    { name: 'SkillVersionDeleteResult', reason: 'dead' },
    { name: 'VersionDeleteFailure', reason: 'dead' },
    { name: 'VersionSweep', reason: 'dead' },
    { name: 'withDuplicateTitleRemedy', reason: 'dead' },
    { name: 'withVersionRootRemedy', reason: 'dead' },
    { name: 'ZipEntryFailure', reason: 'dead' },
    { name: 'ZipInspection', reason: 'dead' },
    { name: 'ZipUnreadable', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/claude/plugin/build.ts', unused: [
    { name: 'ExternalPluginBuildResult', reason: 'dead' },
    { name: 'MarketplaceBuildResult', reason: 'dead' },
    { name: 'PluginBuildCommandOptions', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/claude/plugin/helpers.ts', unused: [
    { name: 'PackageJson', reason: 'dead' },
    { name: 'PackageJsonVat', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/claude/plugin/install.ts', unused: [
    { name: 'PluginInstallCommandOptions', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/claude/plugin/marketplace-json.ts', unused: [
    { name: 'BuildMarketplaceJsonArgs', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/claude/plugin/plugin-files.ts', unused: [
    { name: 'ApplyPluginFilesArgs', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/claude/plugin/plugin-json-merge.ts', unused: [
    { name: 'MergePluginJsonArgs', reason: 'dead' },
    { name: 'MergePluginJsonResult', reason: 'dead' },
    { name: 'ResolveVersionLogger', reason: 'dead' },
    { name: 'VatGeneratedFields', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/claude/plugin/tree-copy.ts', unused: [
    { name: 'RefusedSymlink', reason: 'dead' },
    { name: 'SymlinkRefusalReason', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/consistency-check.ts', unused: [
    { name: 'ConsistencyCheckResult', reason: 'dead' },
    { name: 'isSkillPublished', reason: 'dead' },
    { name: 'matchesSimpleGlob', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/corpus/report.ts', unused: [
    { name: 'computeTotals', reason: 'dead' },
    { name: 'runDirectoryName', reason: 'dead' },
    { name: 'RunTotals', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/corpus/runner.ts', unused: [
    { name: 'AuditDocument', reason: 'dead' },
    { name: 'RunnerOptions', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/corpus/seed.ts', unused: [
    { name: 'Seed', reason: 'dead' },
    { name: 'ValidationAllowEntry', reason: 'dead' },
    { name: 'ValidationBlock', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/doctor.ts', unused: [
    { name: 'DoctorOptions', reason: 'dead' },
    { name: 'DoctorOutcomeCounts', reason: 'dead' },
    { name: 'DoctorResult', reason: 'test-only' },
    { name: 'ProjectContext', reason: 'dead' },
    { name: 'runDoctor', reason: 'dead' },
    { name: 'VersionChecker', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/inventory.ts', unused: [
    { name: 'inventoryCommand', reason: 'dead' },
    { name: 'InventoryCommandOptions', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/mcp/collections.ts', unused: [
    { name: 'AgentCollection', reason: 'dead' },
    { name: 'AgentRegistration', reason: 'dead' },
    { name: 'CollectionModule', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/mcp/list-collections.ts', unused: [
    { name: 'ListCollectionsOptions', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/mcp/serve.ts', unused: [
    { name: 'ServeCommandOptions', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/okf/validate.ts', unused: [
    { name: 'OkfBundleSummary', reason: 'dead' },
    { name: 'OkfBundleSummarySchema', reason: 'dead' },
    { name: 'OkfValidateData', reason: 'dead' },
    { name: 'OkfValidateDataSchema', reason: 'dead' },
    { name: 'okfValidateReport', reason: 'dead' },
    { name: 'OkfValidateReport', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/phase-utils.ts', unused: [
    { name: 'PhaseContext', reason: 'dead' },
    { name: 'phaseIssueCounts', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/rag/index-command.ts', unused: [
    { name: 'IndexOutcome', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/rag/query-command.ts', unused: [
    { name: 'QueryPayloadInput', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/resources/check-supervisor.ts', unused: [
    { name: 'RunResolution', reason: 'dead' },
    { name: 'SupervisedRun', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/resources/check.ts', unused: [
    { name: 'CheckDataSchema', reason: 'dead' },
    { name: 'CheckRunEnding', reason: 'dead' },
    { name: 'ProgressSink', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/resources/scan.ts', unused: [
    { name: 'ScanPayloadInput', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/resources/validate.ts', unused: [
    { name: 'computeDeferredArtifacts', reason: 'dead' },
    { name: 'ValidateOptions', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/skill/review.ts', unused: [
    { name: 'reviewCommand', reason: 'dead' },
    { name: 'SkillReviewCommandOptions', reason: 'dead' },
    { name: 'SkillReviewData', reason: 'dead' },
    { name: 'SkillReviewDataSchema', reason: 'dead' },
    { name: 'SkillReviewReport', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/skill/test/auth-flags.ts', unused: [
    { name: 'RequireAuthValue', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/skill/test/configure.ts', unused: [
    { name: 'SkillTestConfigureOptions', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/skill/test/run.ts', unused: [
    { name: 'BuildDeclaredSkillResult', reason: 'dead' },
    { name: 'ResolvedSubject', reason: 'dead' },
    { name: 'SkillTestRunOptions', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/skills/build.ts', unused: [
    { name: 'BuildStaging', reason: 'dead' },
    { name: 'SkillsBuildCommandOptions', reason: 'dead' },
    { name: 'StagingRecovery', reason: 'dead' },
    { name: 'StagingResidue', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/skills/command-helpers.ts', unused: [
    { name: 'CommandContext', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/skills/install.ts', unused: [
    { name: 'InstallCommandOptions', reason: 'dead' },
    { name: 'InstallError', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/skills/package.ts', unused: [
    { name: 'SkillsPackageCommandOptions', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/skills/scope-guard.ts', unused: [
    { name: 'unscopablePathMessage', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/skills/source-resolvers.ts', unused: [
    { name: 'ResolvedNpmSource', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/skills/validate.ts', unused: [
    { name: 'SkillsValidateRegistryOptions', reason: 'dead' },
    { name: 'ValidatableSkill', reason: 'dead' },
    { name: 'withRunIntegrity', reason: 'test-only' },
  ] },
  { file: 'packages/cli/src/commands/validate.ts', unused: [
    { name: 'ValidateCommandOptions', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/commands/verify.ts', unused: [
    { name: 'VerifyCommandOptions', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/pipeline-oracles/enumeration-snapshot.ts', unused: [
    { name: 'CaptureOptions', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/pipeline-oracles/index.ts', unused: [
    { name: 'CaptureOptions', reason: 'dead' },
    { name: 'CollisionRow', reason: 'dead' },
    { name: 'ConditionFact', reason: 'dead' },
    { name: 'CorpusFiles', reason: 'dead' },
    { name: 'CorpusSymlink', reason: 'dead' },
    { name: 'DANGLING_SYMLINK', reason: 'dead' },
    { name: 'DIRECTORY_LOOP_SYMLINK', reason: 'dead' },
    { name: 'DivergenceClass', reason: 'dead' },
    { name: 'DivergenceRow', reason: 'dead' },
    { name: 'EnumerationRoute', reason: 'dead' },
    { name: 'EnumerationRow', reason: 'dead' },
    { name: 'ESCAPE_TARGET_BASENAME', reason: 'dead' },
    { name: 'ESCAPING_SYMLINK', reason: 'dead' },
    { name: 'HeadingFact', reason: 'dead' },
    { name: 'KeyDisagreement', reason: 'dead' },
    { name: 'LinkFact', reason: 'dead' },
    { name: 'MaterializedCorpus', reason: 'dead' },
    { name: 'MaterializeOptions', reason: 'dead' },
    { name: 'ParseFactRow', reason: 'dead' },
    { name: 'TRAP_CORPUS_FILES', reason: 'dead' },
    { name: 'TRAP_CORPUS_SYMLINKS', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/pipeline-oracles/parse-fact-snapshot.ts', unused: [
    { name: 'PARSE_RESULT_FIELDS_ACCOUNTED_FOR', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/pipeline-oracles/symlink-divergence.ts', unused: [
    { name: 'DivergenceClass', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/pipeline-oracles/trap-corpus.ts', unused: [
    { name: 'CorpusFiles', reason: 'dead' },
    { name: 'CorpusSymlink', reason: 'dead' },
    { name: 'DANGLING_SYMLINK', reason: 'dead' },
    { name: 'DIRECTORY_LOOP_SYMLINK', reason: 'dead' },
    { name: 'ESCAPE_TARGET_BASENAME', reason: 'dead' },
    { name: 'ESCAPING_SYMLINK', reason: 'dead' },
    { name: 'MaterializedCorpus', reason: 'dead' },
    { name: 'MaterializeOptions', reason: 'dead' },
    { name: 'TRAP_CORPUS_FILES', reason: 'dead' },
    { name: 'TRAP_CORPUS_SYMLINKS', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/qa-snapshot/capture.ts', unused: [
    { name: 'CaptureRequest', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/qa-snapshot/normalize.ts', unused: [
    { name: 'PathSubstitution', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/qa-snapshot/store.ts', unused: [
    { name: 'SnapshotPaths', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/report-schemas.ts', unused: [
    { name: 'ReportEntry', reason: 'dead' },
    { name: 'ReportSchemaEntry', reason: 'dead' },
    { name: 'UnmigratedEntry', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/skill-resolution/classify.ts', unused: [
    { name: 'TokenShape', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/skill-resolution/index.ts', unused: [
    { name: 'classifyToken', reason: 'dead' },
    { name: 'getDiscoveredSkillsByPath', reason: 'dead' },
    { name: 'parseSourceSpec', reason: 'dead' },
    { name: 'resolveSkillPackagingConfig', reason: 'dead' },
    { name: 'SkillDistribution', reason: 'dead' },
    { name: 'SkillReference', reason: 'dead' },
    { name: 'stripValidationAllowForDisplay', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/utils/agent-runner.ts', unused: [
    { name: 'RunAgentOptions', reason: 'dead' },
    { name: 'RunAgentResult', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/utils/command-error.ts', unused: [
    { name: 'buildValidationGateFailure', reason: 'dead' },
    { name: 'CommandErrorDocument', reason: 'dead' },
    { name: 'ValidationGateFailure', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/utils/config-loader.ts', unused: [
    { name: 'getConfigDir', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/utils/context-budget-issues.ts', unused: [
    { name: 'ScopedSweep', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/utils/edge-lens-evaluation.ts', unused: [
    { name: 'EVALUATED_LENS_RELATIONS', reason: 'dead' },
    { name: 'EvaluatedLenses', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/utils/output.ts', unused: [
    { name: 'WriteAllSyncOptions', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/utils/population-wiring.ts', unused: [
    { name: 'PopulationWiring', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/utils/projection-query.ts', unused: [
    { name: 'PreflightStatement', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/utils/projection-store.ts', unused: [
    { name: 'OpenedPopulationCache', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/utils/relativize-paths.ts', unused: [
    { name: 'PathEntry', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/utils/resource-loader.ts', unused: [
    { name: 'ResourceLoadResult', reason: 'dead' },
    { name: 'resourcesProjectionCrawlSelected', reason: 'dead' },
    { name: 'scopeIncludeToSubtree', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/utils/root-argv.ts', unused: [
    { name: 'RootArgvGrammar', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/utils/run-integrity.ts', unused: [
    { name: 'RUN_INTEGRITY_CODE', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/utils/skill-quality-footer.ts', unused: [
    { name: 'SKILL_QUALITY_FOOTER_CODES', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/utils/sqlite-experimental-warning.ts', unused: [
    { name: 'RestoreWarningEmitter', reason: 'dead' },
  ] },
  { file: 'packages/cli/src/utils/verdict-helpers.ts', unused: [
    { name: 'verdictToIssue', reason: 'dead' },
  ] },
  { file: 'packages/cli/test/anchor-contract-helpers.ts', unused: [
    { name: 'AnchorSighting', reason: 'dead' },
    { name: 'collectAnchors', reason: 'dead' },
  ] },
  { file: 'packages/cli/test/helpers/upload-logger.ts', unused: [
    { name: 'RecordedLog', reason: 'dead' },
  ] },
  { file: 'packages/cli/test/helpers/vat-doctor-test-helpers.ts', unused: [
    { name: 'DoctorConfigMockConfig', reason: 'dead' },
    { name: 'DoctorEnvironmentConfig', reason: 'dead' },
    { name: 'DoctorFileSystemConfig', reason: 'dead' },
    { name: 'DoctorResult', reason: 'dead' },
    { name: 'findCheck', reason: 'dead' },
  ] },
  { file: 'packages/cli/test/integration/audit-settings-fixture.ts', unused: [
    { name: 'CompatibilityBlock', reason: 'dead' },
    { name: 'SettingsBlock', reason: 'dead' },
  ] },
  { file: 'packages/cli/test/pipeline-oracles/helpers/corpus-fixture.ts', unused: [
    { name: 'CorpusFixture', reason: 'dead' },
  ] },
  { file: 'packages/cli/test/system/audit-test-helpers.ts', unused: [
    { name: 'compareStrings', reason: 'dead' },
    { name: 'sortTuples', reason: 'dead' },
    { name: 'toCorpusRelative', reason: 'dead' },
  ] },
  { file: 'packages/cli/test/system/rag-test-setup.ts', unused: [
    { name: 'afterAll', reason: 'dead' },
    { name: 'beforeAll', reason: 'dead' },
    { name: 'setupIndexedRagTest', reason: 'dead' },
  ] },
  { file: 'packages/cli/test/system/test-common.ts', unused: [
    { name: 'createSkillsPackageJson', reason: 'dead' },
    { name: 'TestVatSkill', reason: 'dead' },
  ] },
  { file: 'packages/cli/test/system/test-fixture-loader.ts', unused: [
    { name: 'getTestFixturesPathSync', reason: 'dead' },
  ] },
  { file: 'packages/cli/test/system/test-helpers/cli-runner.ts', unused: [
    { name: 'executeCliAndParseYaml', reason: 'dead' },
  ] },
  { file: 'packages/cli/test/system/test-helpers/frontmatter-setup.ts', unused: [
    { name: 'executeResourcesValidateWithSchema', reason: 'dead' },
  ] },
  { file: 'packages/cli/test/system/test-helpers/index.ts', unused: [
    { name: 'CliResult', reason: 'dead' },
    { name: 'createInstalledSkillDir', reason: 'dead' },
    { name: 'createTempProject', reason: 'dead' },
    { name: 'executeCliAndParseYaml', reason: 'dead' },
    { name: 'executeResourcesValidateWithSchema', reason: 'dead' },
    { name: 'setupDevTestProject', reason: 'dead' },
    { name: 'setupIndexedRagTest', reason: 'dead' },
    { name: 'TestProjectOptions', reason: 'dead' },
  ] },
  { file: 'packages/cli/test/system/test-helpers/project-setup.ts', unused: [
    { name: 'createTempProject', reason: 'dead' },
    { name: 'TestProjectOptions', reason: 'dead' },
  ] },
  { file: 'packages/cli/test/system/test-helpers/rag-setup.ts', unused: [
    { name: 'setupIndexedRagTest', reason: 'dead' },
  ] },
  { file: 'packages/cli/test/system/test-helpers/skills-setup.ts', unused: [
    { name: 'createInstalledSkillDir', reason: 'dead' },
    { name: 'setupDevTestProject', reason: 'dead' },
  ] },
  { file: 'packages/dev-tools/test/test-helpers.ts', unused: [
    { name: 'assertValidSemver', reason: 'dead' },
    { name: 'MockPackageOptions', reason: 'dead' },
    { name: 'TestTempDirOptions', reason: 'dead' },
  ] },
  { file: 'packages/discovery/src/filters/pattern-filter.ts', unused: [
    { name: 'PatternFilterOptions', reason: 'dead' },
  ] },
  { file: 'packages/lab/src/facets/population/types.ts', unused: [
    { name: 'populationEntryShape', reason: 'dead' },
  ] },
  { file: 'packages/lab/src/harness/facet-compare.ts', unused: [
    { name: 'bothSides', reason: 'dead' },
    { name: 'CountDelta', reason: 'dead' },
    { name: 'MsDelta', reason: 'dead' },
    { name: 'RowMovementKind', reason: 'dead' },
  ] },
  { file: 'packages/lab/test/capture-fixtures.ts', unused: [
    { name: 'ExpectedStamp', reason: 'dead' },
  ] },
  { file: 'packages/lab/test/git-fixtures.ts', unused: [
    { name: 'COMMIT_CONFIG', reason: 'dead' },
  ] },
  { file: 'packages/lab/test/parse-fixtures.ts', unused: [
    { name: 'defaultHtmlKind', reason: 'dead' },
    { name: 'KINDS', reason: 'dead' },
  ] },
  { file: 'packages/rag-lancedb/src/document-helpers.ts', unused: [
    { name: 'DocumentColumnTypeMismatch', reason: 'dead' },
    { name: 'MissingDocumentColumn', reason: 'dead' },
  ] },
  { file: 'packages/rag-lancedb/src/schema.ts', unused: [
    { name: 'chunkToLanceRowWithDefaultMetadata', reason: 'dead' },
    { name: 'lanceRowToChunkWithDefaultMetadata', reason: 'dead' },
  ] },
  { file: 'packages/rag/src/embedding-providers/onnx-utils.ts', unused: [
    { name: 'BatchTokenizerOutput', reason: 'dead' },
    { name: 'SpecialTokenIds', reason: 'dead' },
    { name: 'TokenizerOutput', reason: 'dead' },
  ] },
  { file: 'packages/rag/src/interfaces/provider.ts', unused: [
    { name: 'RAGChunk', reason: 'dead' },
  ] },
  { file: 'packages/rag/src/schemas/index.ts', unused: [
    { name: 'IndexResult', reason: 'dead' },
    { name: 'RAGChunk', reason: 'dead' },
    { name: 'RAGQuery', reason: 'dead' },
    { name: 'RAGResult', reason: 'dead' },
    { name: 'RAGStats', reason: 'dead' },
  ] },
  { file: 'packages/resource-compiler/src/language-service/completions.ts', unused: [
    { name: 'getCompletionEntryDetails', reason: 'dead' },
  ] },
  { file: 'packages/resource-compiler/src/language-service/utils.ts', unused: [
    { name: 'enhanceLanguageServiceOperation', reason: 'dead' },
    { name: 'getPropertyNameNode', reason: 'dead' },
    { name: 'resolveAndLoadFragment', reason: 'dead' },
    { name: 'withFragmentResolution', reason: 'dead' },
  ] },
  { file: 'packages/resource-compiler/src/transformer/transformer.ts', unused: [
    { name: 'default', reason: 'test-only' },
    { name: 'TransformerOptions', reason: 'dead' },
  ] },
  { file: 'packages/resource-compiler/src/utils/copy-resources.ts', unused: [
    { name: 'CopyResourcesOptions', reason: 'dead' },
  ] },
  { file: 'packages/resource-compiler/src/utils/index.ts', unused: [
    { name: 'copyResources', reason: 'dead' },
    { name: 'CopyResourcesOptions', reason: 'dead' },
  ] },
  { file: 'packages/resource-compiler/test/transformer/test-helpers.ts', unused: [
    { name: 'getFirstImport', reason: 'dead' },
  ] },
  { file: 'packages/resources/src/content-cache.ts', unused: [
    { name: 'ContentCacheEntry', reason: 'dead' },
  ] },
  { file: 'packages/resources/src/external-link-validator.ts', unused: [
    { name: 'ExternalLinkValidatorOptions', reason: 'dead' },
    { name: 'isAliveStatus', reason: 'dead' },
    { name: 'LinkValidationResult', reason: 'dead' },
  ] },
  { file: 'packages/resources/src/frontmatter-link-validator.ts', unused: [
    { name: 'FrontmatterLinkValidationResult', reason: 'dead' },
  ] },
  { file: 'packages/resources/src/html-link-parser.ts', unused: [
    { name: 'HtmlDocument', reason: 'dead' },
    { name: 'P5Attribute', reason: 'test-only' },
  ] },
  { file: 'packages/resources/src/link-auth-classify.ts', unused: [
    { name: 'LinkAuthOutcome', reason: 'dead' },
  ] },
  { file: 'packages/resources/src/link-auth-config-build.ts', unused: [
    { name: '_assertSchemaKeysAgreeWithEngine', reason: 'dead' },
  ] },
  { file: 'packages/resources/src/link-auth/transforms.ts', unused: [
    { name: 'TransformName', reason: 'dead' },
  ] },
  { file: 'packages/resources/src/link-validator.ts', unused: [
    { name: 'AnchorCheck', reason: 'dead' },
    { name: 'FileVerification', reason: 'dead' },
    { name: 'fragmentIndexEntry', reason: 'dead' },
    { name: 'isHtmlPath', reason: 'dead' },
    { name: 'pathCorrection', reason: 'dead' },
    { name: 'PathCorrection', reason: 'dead' },
    { name: 'UnreadableTarget', reason: 'dead' },
  ] },
  { file: 'packages/resources/src/okf/findings.ts', unused: [
    { name: 'IndexInspection', reason: 'dead' },
  ] },
  { file: 'packages/resources/src/parse-conformance.ts', unused: [
    { name: 'ConformanceDocument', reason: 'dead' },
    { name: 'ConformanceReport', reason: 'dead' },
  ] },
  { file: 'packages/resources/src/parse-pool.ts', unused: [
    { name: 'ParseWireFacts', reason: 'dead' },
    { name: 'ParseWorkerData', reason: 'dead' },
    { name: 'ParseWorkerFailure', reason: 'dead' },
    { name: 'ParseWorkerRequest', reason: 'dead' },
    { name: 'ParseWorkerResponse', reason: 'dead' },
    { name: 'ParseWorkerTimingReport', reason: 'dead' },
  ] },
  { file: 'packages/resources/src/parse-timing.ts', unused: [
    { name: 'ParseKindShape', reason: 'dead' },
    { name: 'ParsePassSlot', reason: 'dead' },
    { name: 'ParserKindSlot', reason: 'dead' },
    { name: 'readThreadTiming', reason: 'dead' },
    { name: 'TierPassSlot', reason: 'dead' },
  ] },
  { file: 'packages/resources/src/parse-tokenize-probe.ts', unused: [
    { name: 'TokenizeEvents', reason: 'dead' },
    { name: 'TokenizeProbeOrder', reason: 'dead' },
  ] },
  { file: 'packages/resources/src/projection/claude-context-ancestry.ts', unused: [
    { name: 'AncestryEntry', reason: 'dead' },
  ] },
  { file: 'packages/resources/src/projection/claude-context-rules.ts', unused: [
    { name: 'RuleSelectionResult', reason: 'dead' },
    { name: 'SelectedRule', reason: 'dead' },
  ] },
  { file: 'packages/resources/src/projection/identity.ts', unused: [
    { name: 'CanonicalPathContext', reason: 'dead' },
  ] },
  { file: 'packages/resources/src/reference-lexer.ts', unused: [
    { name: 'stripLeadingDelimiters', reason: 'dead' },
    { name: 'stripTrailingPunctuation', reason: 'test-only' },
  ] },
  { file: 'packages/resources/src/remark-parser.ts', unused: [
    { name: 'RemarkSession', reason: 'dead' },
  ] },
  { file: 'packages/resources/src/resource-registry.ts', unused: [
    { name: 'ValidateOptions', reason: 'dead' },
  ] },
  { file: 'packages/resources/src/scan-lines.ts', unused: [
    { name: 'MAX_SCANNED_LINE_LENGTH', reason: 'dead' },
  ] },
  { file: 'packages/resources/src/schemas/link-auth.ts', unused: [
    { name: 'LinkAuthCacheSchema', reason: 'dead' },
    { name: 'ProviderAuthSchema', reason: 'dead' },
    { name: 'ProviderCheckSchema', reason: 'dead' },
    { name: 'ProviderEntry', reason: 'dead' },
    { name: 'ProviderFetchSchema', reason: 'dead' },
    { name: 'ProviderMatchSchema', reason: 'dead' },
    { name: 'RewriteRule', reason: 'dead' },
    { name: 'TokenSource', reason: 'dead' },
  ] },
  { file: 'packages/resources/src/schemas/project-config.ts', unused: [
    { name: 'ClaudeMarketplacePublish', reason: 'dead' },
    { name: 'ClaudeMarketplacePublishSchema', reason: 'dead' },
    { name: 'ExcludeReferenceRuleSchema', reason: 'dead' },
    { name: 'ExcludeReferencesFromBundleSchema', reason: 'dead' },
    { name: 'ExternalUrlValidation', reason: 'dead' },
    { name: 'ExternalUrlValidationSchema', reason: 'dead' },
    { name: 'SkillTestGlobalConfig', reason: 'dead' },
    { name: 'ValidationConfigSchema', reason: 'test-only' },
  ] },
  { file: 'packages/resources/src/types.ts', unused: [
    { name: 'addCLISchema', reason: 'dead' },
    { name: 'addCollectionSchema', reason: 'dead' },
    { name: 'assignSchemas', reason: 'dead' },
    { name: 'BaseResource', reason: 'dead' },
    { name: 'classifyLink', reason: 'test-only' },
    { name: 'CollectionStat', reason: 'dead' },
    { name: 'CollectionStats', reason: 'dead' },
    { name: 'CrawlOptions', reason: 'dead' },
    { name: 'expandPattern', reason: 'dead' },
    { name: 'expandPatterns', reason: 'dead' },
    { name: 'FrontmatterExternalUrl', reason: 'dead' },
    { name: 'FrontmatterLinkValidationResult', reason: 'dead' },
    { name: 'getAllSchemaErrors', reason: 'dead' },
    { name: 'getCollectionsForFile', reason: 'dead' },
    { name: 'getResourceAbsolutePath', reason: 'dead' },
    { name: 'hasSchemaErrors', reason: 'dead' },
    { name: 'Heading', reason: 'test-only' },
    { name: 'isGlobPattern', reason: 'dead' },
    { name: 'isJsonSchema', reason: 'dead' },
    { name: 'isValidProjectPath', reason: 'dead' },
    { name: 'JsonResource', reason: 'dead' },
    { name: 'JsonSchemaResource', reason: 'dead' },
    { name: 'loadConfig', reason: 'dead' },
    { name: 'MarkdownResource', reason: 'dead' },
    { name: 'matchesCollection', reason: 'dead' },
    { name: 'normalizeProjectPath', reason: 'dead' },
    { name: 'parseConfigFile', reason: 'dead' },
    { name: 'RegistryStats', reason: 'dead' },
    { name: 'Resource', reason: 'dead' },
    { name: 'ResourceRegistryOptions', reason: 'dead' },
    { name: 'ResourceType', reason: 'dead' },
    { name: 'SHA256', reason: 'dead' },
    { name: 'SHA256Schema', reason: 'dead' },
    { name: 'validateFrontmatterLinks', reason: 'dead' },
    { name: 'validateFrontmatterMultiSchema', reason: 'dead' },
    { name: 'validateLink', reason: 'test-only' },
    { name: 'ValidateLinkOptions', reason: 'test-only' },
    { name: 'ValidateOptions', reason: 'dead' },
    { name: 'YamlResource', reason: 'dead' },
  ] },
  { file: 'packages/resources/src/types/resources.ts', unused: [
    { name: 'BaseResource', reason: 'dead' },
    { name: 'Heading', reason: 'dead' },
    { name: 'JsonResource', reason: 'dead' },
    { name: 'JsonSchemaResource', reason: 'dead' },
    { name: 'MarkdownResource', reason: 'dead' },
    { name: 'Resource', reason: 'dead' },
    { name: 'YamlResource', reason: 'dead' },
  ] },
  { file: 'packages/resources/src/unresolved-references.ts', unused: [
    { name: 'isRangeFullyMasked', reason: 'dead' },
    { name: 'ReferenceOccurrence', reason: 'dead' },
  ] },
  { file: 'packages/runtime-claude-agent-sdk/src/adapters/common-helpers.ts', unused: [
    { name: 'convertAgentToTool', reason: 'dead' },
  ] },
  { file: 'packages/runtime-openai/src/adapters/common-helpers.ts', unused: [
    { name: 'extractTextFromResponse', reason: 'test-only' },
  ] },
  { file: 'packages/utils/src/crawl-timing.ts', unused: [
    { name: 'CRAWL_CHARGEABLE_IDS', reason: 'dead' },
  ] },
  { file: 'packages/utils/src/file-crawler.ts', unused: [
    { name: 'RefuseListingContext', reason: 'dead' },
  ] },
  { file: 'packages/utils/src/fs.ts', unused: [
    { name: 'ComponentMatch', reason: 'dead' },
    { name: 'DecodedText', reason: 'dead' },
    { name: 'DirectorySpellingIndex', reason: 'dead' },
    { name: 'EncodingSource', reason: 'dead' },
    { name: 'FilenameMatch', reason: 'dead' },
    { name: 'isPathAbsentError', reason: 'dead' },
    { name: 'PathProbe', reason: 'dead' },
    { name: 'PathProbeStats', reason: 'dead' },
    { name: 'PathSpelling', reason: 'dead' },
    { name: 'PathSpellingRequest', reason: 'dead' },
    { name: 'PathSpellingTable', reason: 'dead' },
    { name: 'RealpathTable', reason: 'dead' },
    { name: 'spellingWalkRoot', reason: 'dead' },
    { name: 'TextEncoding', reason: 'dead' },
    { name: 'TextProvenance', reason: 'dead' },
  ] },
  { file: 'packages/utils/src/git-run.ts', unused: [
    { name: 'GitRunOptions', reason: 'dead' },
  ] },
  { file: 'packages/utils/src/git-snapshot.ts', unused: [
    { name: 'GitSnapshotEntry', reason: 'dead' },
    { name: 'GitTreeSnapshot', reason: 'dead' },
  ] },
  { file: 'packages/utils/src/git-tracker.ts', unused: [
    { name: 'GitTrackerInitOptions', reason: 'dead' },
  ] },
  { file: 'packages/utils/src/git-url.ts', unused: [
    { name: 'NonInteractiveGitOverrides', reason: 'dead' },
  ] },
  { file: 'packages/utils/src/git-utils.ts', unused: [
    { name: 'GitListingOptions', reason: 'dead' },
  ] },
  { file: 'packages/utils/src/git.ts', unused: [
    { name: 'GitRunOptions', reason: 'dead' },
    { name: 'GitSnapshotEntry', reason: 'dead' },
    { name: 'GitTrackerInitOptions', reason: 'dead' },
    { name: 'GitTreeSnapshot', reason: 'dead' },
    { name: 'NonInteractiveGitOverrides', reason: 'dead' },
    { name: 'peekGitTreeSnapshot', reason: 'dead' },
    { name: 'RefuseListingContext', reason: 'dead' },
    { name: 'UnreadablePolicy', reason: 'dead' },
  ] },
  { file: 'packages/utils/src/path-core.ts', unused: [
    { name: 'isSingleFsSegment', reason: 'dead' },
    { name: 'PathEscapesRootError', reason: 'dead' },
    { name: 'relativeEscapesRoot', reason: 'dead' },
  ] },
  { file: 'packages/utils/src/path.ts', unused: [
    { name: 'isSingleFsSegment', reason: 'dead' },
    { name: 'PathEscapesRootError', reason: 'dead' },
    { name: 'relativeEscapesRoot', reason: 'dead' },
    { name: 'toNfc', reason: 'dead' },
  ] },
  { file: 'packages/utils/src/process.ts', unused: [
    { name: 'hasShellSyntax', reason: 'dead' },
    { name: 'safeExecFromString', reason: 'dead' },
    { name: 'SafeExecOptions', reason: 'dead' },
    { name: 'SafeExecResult', reason: 'dead' },
    { name: 'StdioBlockingResult', reason: 'dead' },
  ] },
  { file: 'packages/utils/src/safe-exec.ts', unused: [
    { name: 'SafeExecOptions', reason: 'dead' },
    { name: 'SafeExecResult', reason: 'dead' },
  ] },
  { file: 'packages/utils/src/skill-test/auth-resolver.ts', unused: [
    { name: 'ResolveAuthOptions', reason: 'dead' },
  ] },
  { file: 'packages/utils/src/skill-test/env-scrub.ts', unused: [
    { name: 'DeclaredEnvInput', reason: 'dead' },
    { name: 'DeclaredEnvResult', reason: 'dead' },
    { name: 'ForwardEnvOptions', reason: 'dead' },
  ] },
  { file: 'packages/utils/src/skill-test/index.ts', unused: [
    { name: 'AuthStatusResult', reason: 'dead' },
    { name: 'buildForwardedEnv', reason: 'dead' },
    { name: 'ClaudeSpawnArgs', reason: 'dead' },
    { name: 'DeclaredEnvInput', reason: 'dead' },
    { name: 'DeclaredEnvResult', reason: 'dead' },
    { name: 'ForwardEnvOptions', reason: 'dead' },
    { name: 'ResolveAuthOptions', reason: 'dead' },
  ] },
  { file: 'packages/utils/src/skill-test/spawn-claude.ts', unused: [
    { name: 'ClaudeSpawnArgs', reason: 'dead' },
  ] },
  { file: 'packages/utils/src/stdio-blocking.ts', unused: [
    { name: 'StdioBlockingResult', reason: 'dead' },
  ] },
  { file: 'packages/utils/src/test-helpers.ts', unused: [
    { name: 'RefusableAsyncFsMethod', reason: 'dead' },
    { name: 'RefusableSyncFsMethod', reason: 'dead' },
  ] },
  { file: 'packages/utils/src/testing.ts', unused: [
    { name: 'ReplantableCorpus', reason: 'dead' },
    { name: 'TempCorpus', reason: 'dead' },
  ] },
  { file: 'packages/utils/src/testing/temp-dir.ts', unused: [
    { name: 'getTestOutputBase', reason: 'dead' },
    { name: 'RemoveScratchDirOptions', reason: 'dead' },
  ] },
  { file: 'packages/utils/src/text.ts', unused: [
    { name: 'DecodedText', reason: 'dead' },
    { name: 'EncodingSource', reason: 'dead' },
    { name: 'TextEncoding', reason: 'dead' },
  ] },
  { file: 'packages/utils/src/yaml/surgical-yaml.ts', unused: [
    { name: 'YamlPath', reason: 'dead' },
  ] },
  { file: 'packages/vat-example-cat-agents/examples/conversational-adapters/shared-helpers.ts', unused: [
    { name: 'BreedAdvisorContext', reason: 'dead' },
  ] },
  { file: 'packages/vat-example-cat-agents/test/test-helpers.ts', unused: [
    { name: 'expectError', reason: 'dead' },
    { name: 'expectSuccess', reason: 'dead' },
    { name: 'findHaikuWithKeywords', reason: 'dead' },
    { name: 'findInvalidSyllableLine', reason: 'dead' },
    { name: 'findMatchingContent', reason: 'dead' },
    { name: 'TEST_CATS', reason: 'dead' },
  ] },
  { file: 'vitest.shared.ts', unused: [
    { name: 'integrationExecArgv', reason: 'dead' },
    { name: 'integrationPool', reason: 'dead' },
    { name: 'IntegrationTestConfigOverrides', reason: 'dead' },
    { name: 'platformTestTimeout', reason: 'dead' },
    { name: 'SystemTestConfigOverrides', reason: 'dead' },
    { name: 'UnitTestConfigOverrides', reason: 'dead' },
    { name: 'WINDOWS_EXCLUDED_CLI_SYSTEM_TESTS', reason: 'dead' },
  ] },
];
