name: Coverage Reporting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    name: Upload Coverage to Codecov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup toolchain
        uses: ./.github/actions/setup

      - name: Run tests with coverage
        run: bun run test:coverage
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: true
          verbose: true
